import admin = require('firebase-admin');
import { onDocumentCreated, onDocumentWritten } from "firebase-functions/v2/firestore";
import { getTenAtATime } from '../95_gen2/gen2';
import { Filter } from 'firebase-admin/firestore';
let usersCollectionString = 'testCollectionUsers';

export const users_knowing_gen2_export = onDocumentWritten(`usersKnowing/{docId}`, async (event) => {
    const db: FirebaseFirestore.Firestore = admin.firestore()
    if (event == undefined || event.data == undefined || event.data.after == undefined) return
    const data: FirebaseFirestore.DocumentData | undefined = event.data.after.data()

    try {
        if (data == null || data == undefined || data.status != 'pending') return;

        let targetNumbersRaw: string[] = data.targetNumbers ?? []
        let targetNumbers: string[] = []

        const toRemove: string[] = ['+917841877781', '+918799951362', '+918799967349', '+918459714096', '+918080528893', '+918459714092', '+918799951359', '+919699893063']

        for (let i = 0; i < targetNumbersRaw.length; i++)
            if (!toRemove.includes(targetNumbersRaw[i])) targetNumbers.push(targetNumbersRaw[i])

        console.log(`Found ${targetNumbersRaw.length} raw and ${targetNumbers.length} target numbers`)

        if (targetNumbers.length == 0 || targetNumbers.length > 30) {
            await event.data.after.ref.update({
                'errors': admin.firestore.FieldValue.arrayUnion(`${targetNumbers.length} target numbers found so ending`),
                'status': 'done'
            });
            return
        }

        let q;

        if (targetNumbers.length > 20) {
            const arrayOne = getTenAtATime(targetNumbers, 0)
            const arrayTwo = getTenAtATime(targetNumbers, 1)
            const arrayThree = getTenAtATime(targetNumbers, 2)

            q = await db.collection(usersCollectionString)
                .where(
                    Filter.or(
                        Filter.where('contactsArrayFresh', 'array-contains-any', arrayOne),
                        Filter.where('contactsArrayFresh', 'array-contains-any', arrayTwo),
                        Filter.where('contactsArrayFresh', 'array-contains-any', arrayThree)))
                .get();
        } else if (targetNumbers.length > 10) {
            const arrayOne = getTenAtATime(targetNumbers, 0)
            const arrayTwo = getTenAtATime(targetNumbers, 1)

            q = await db.collection(usersCollectionString)
                .where(
                    Filter.or(
                        Filter.where('contactsArrayFresh', 'array-contains-any', arrayOne),
                        Filter.where('contactsArrayFresh', 'array-contains-any', arrayTwo)))
                .get();
        } else {
            q = await db.collection(usersCollectionString).where('contactsArrayFresh', 'array-contains-any', targetNumbers).get()
        }

        let idsNumbersMap: Map<string, string> = new Map()
        let count: number = 0

        for (const doc of q.docs) {
            try {
                const uData = doc.data()
                if (uData != null && uData != undefined && uData.ownNumber != null && uData.ownNumber != undefined && uData.ownNumber != '') {
                    idsNumbersMap.set(doc.id, uData.ownNumber!)
                    // console.log(`Added ${uData.ownNumber!}`)
                    count++
                } else {
                    console.log(`E4: uData is missing for ${doc.id}`)
                }
            } catch (e) {
                if (e instanceof Error)
                    console.log(`Error 1: ${e.toString()}`)
            }
        }

        console.log(`Error 1: map: ${idsNumbersMap.keys.length}, q.docs: ${q.docs.length}`)

        // if (idsNumbersMap.keys.length == 0) {
        //     await event.data.after.ref.update({
        //         'status': 'done',
        //         'errors': admin.firestore.FieldValue.arrayUnion(`E2: idsNumbersMap is empty, q.docs: ${q.docs.length}`),
        //     });
        //     return;
        // }

        let idsNumbersMapForUploading = Array.from(idsNumbersMap).reduce((obj, [key, value]) => (Object.assign(obj, { [key]: value })), {});

        await event.data.after.ref.update({
            'status': 'done',
            'usersKnowingTargets': idsNumbersMapForUploading,
            'count': count,
        });
        return

    } catch (e) {
        if (e instanceof Error)
            await event.data.after.ref.update({
                'errors': admin.firestore.FieldValue.arrayUnion(`E3: ${e.toString()}`),
                'status': 'done'
            });
    }

    return
});

export const new_user_added_export = onDocumentCreated(`testUsersAutoGenerated/{userId}`, async (event) => {
    if (event == undefined || event.data == undefined) return
    const triggerData: FirebaseFirestore.DocumentData | undefined = event.data.data()
    // const db: FirebaseFirestore.Firestore = admin.firestore()
    if (triggerData == null || triggerData == undefined) return;

    try {
        if (triggerData.createdAt == null || triggerData.createdAt == undefined) {
            await event.data.ref.update({ 'createdAt': Date.now() });
        }
    } catch (e) {
        console.log(`Error 1: ${e!.toString()}`)
    }

    if (triggerData.phoneNumber == null || triggerData.phoneNumber == undefined || triggerData.phoneNumber == '') {
        return
    }

    // console.log(`${triggerData.phoneNumber} 01 started`)
    // const aucApprovals = await db.collection('auctionApprovals').get()
    // console.log(`${triggerData.phoneNumber} 02 found aucApproval docs total ${aucApprovals.docs.length}`)
    // try {
    //     for (const approvalDoc of aucApprovals.docs) {
    //         const data = approvalDoc.data()
    //         if (data != null && data != undefined && data.individualsMap != null && data.individualsMap != undefined) {
    //             const individualsMap = data.individualsMap!
    //             const individualsMapObject: Map<string, any> = new Map(Object.entries(individualsMap));
    //             const applicantKeys = Array.from(individualsMapObject.keys())

    //             try {
    //                 console.log(`${triggerData.phoneNumber} 03 for cId ${approvalDoc.id}`)

    //                 for (const tentativelyBrokerKey of applicantKeys) {
    //                     const indiMap = individualsMapObject.get(tentativelyBrokerKey)
    //                     // console.log(`${triggerData.phoneNumber} 04 for cId ${doc.id} > brokerKey ${tentativelyBrokerKey}`)

    //                     if (indiMap != null && indiMap != undefined && indiMap.applicationStatus == 'approved' && indiMap.approvedBroker == true) {
    //                         console.log(`${triggerData.phoneNumber} 04 for cId ${approvalDoc.id} > brokerKey ${tentativelyBrokerKey} is an approved broker`)

    //                         const indiMapObject: Map<string, any> = new Map(Object.entries(indiMap));
    //                         // const indiParameterKeys = Array.from(indiMapObject.keys())
    //                         const tentativelyBrokerName = indiMapObject.get('name') ?? '';
    //                         const tentativelyBrokerNumber = indiMapObject.get('number') ?? '';
    //                         try {
    //                             if (indiMapObject.get('privatelyApproved') != null && indiMapObject.get('privatelyApproved') != undefined) {
    //                                 const privatelyApprovedObject: Map<string, any> = new Map(Object.entries(indiMapObject.get('privatelyApproved')))!;
    //                                 const privatelyApprovedKeys = Array.from(privatelyApprovedObject.keys())

    //                                 for (const num of privatelyApprovedKeys) {
    //                                     try {
    //                                         if (num == triggerData.phoneNumber && privatelyApprovedObject.get(num) == '') {
    //                                             // newly joined user whose broker approval docs need to be created

    //                                             const newUserId = event.data.id
    //                                             const brResDoc = await approvalDoc.ref.collection('brokerResponses').doc(newUserId).get()
    //                                             if (!brResDoc.exists) {
    //                                                 // const companyDocDataMap: Map<string, any> = new Map(Object.entries(companyDocData))
    //                                                 // let companyDocDataMapObject = Array.from(companyDocDataMap).reduce((obj, [key, value]) => (Object.assign(obj, { [key]: value })), {});
    //                                                 try {
    //                                                     await brResDoc.ref.set(
    //                                                         {
    //                                                             'applicantNumber': triggerData.phoneNumber,
    //                                                             'brokerIds': [tentativelyBrokerKey],
    //                                                             'brokers': {
    //                                                                 [tentativelyBrokerKey]: {
    //                                                                     'brokerName': tentativelyBrokerName,
    //                                                                     'brokerNumber': tentativelyBrokerNumber,
    //                                                                     'status': 'approved',
    //                                                                     'history': ['Auto-approved when the bidder joined Khoj as they were privately added by broker']
    //                                                                 }
    //                                                             }
    //                                                         }
    //                                                     )
    //                                                 } catch (e) {
    //                                                     console.log(`Error 6: ${e!.toString()}`)
    //                                                 }
    //                                             } else {
    //                                                 try {
    //                                                     const path = `brokers.${tentativelyBrokerKey}`
    //                                                     const pathForHistory = `${path}.history`
    //                                                     await brResDoc.ref.update({
    //                                                         'applicantNumber': triggerData.phoneNumber,
    //                                                         'brokerIds': admin.firestore.FieldValue.arrayUnion([tentativelyBrokerKey]),
    //                                                         [path]: {
    //                                                             'brokerName': tentativelyBrokerName,
    //                                                             'brokerNumber': tentativelyBrokerNumber,
    //                                                             'status': 'approved',
    //                                                         },
    //                                                         [pathForHistory]: admin.firestore.FieldValue.arrayUnion(
    //                                                             `Auto-approved on ${getDateTimeString(Date.now())} when the bidder joined Khoj as earlier they were privately added by the broker ${tentativelyBrokerNumber}`
    //                                                         ),
    //                                                     })
    //                                                 } catch (e) {
    //                                                     console.log(`Error 7: ${e!.toString()}`)
    //                                                 }
    //                                             }

    //                                             try {
    //                                                 const path = `individualsMap.${tentativelyBrokerKey}.privatelyApproved.${triggerData.phoneNumber}`
    //                                                 await approvalDoc.ref.update({ [path]: event.data.id })
    //                                             } catch (e) {
    //                                                 console.log(`Error 9: ${e!.toString()}`)
    //                                             }
    //                                         }
    //                                     } catch (e) {
    //                                         console.log(`Error 5: ${e!.toString()}`)
    //                                     }
    //                                 }
    //                             }
    //                         } catch (e) {
    //                             console.log(`Error 4: ${e!.toString()}`)
    //                         }
    //                     }
    //                 }
    //             } catch (e) {
    //                 console.log(`Error 3: ${e!.toString()}`)
    //             }
    //         }
    //     }
    // } catch (e) {
    //     console.log(`Error 2: ${e!.toString()}`)
    // }

    return
});
